FROM ruby:2.7.1-alpine

LABEL maintainer="sachin@kodelounge.com"

RUN apk add --no-cache --virtual build-dependencies \
  build-base \
  gcc \
  wget \
  git \
  mariadb-dev \
  nodejs \
  tzdata \
  imagemagick6 \
  imagemagick6-dev \
  imagemagick6-c++ \
  openjdk8-jre \
  bash